packages:
  - docs
  - sdk/native
  - codex-cli
  - codex-rs/responses-api-proxy/npm
  - sdk/typescript
  - sdk/native
  - multi-agent-codex-system
  - diff-agent

ignoredBuiltDependencies:
  - esbuild
